databases:
  - name: sokoban_levels
    databaseName: sokoban_levels
    user: sokoban_levels

services:
  - type: web
    name: sokoban_levels
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sokoban_levels.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sokoban_levels
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
